name: CapyMOA Test and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # TODO: moa tests are sensitive to java versions https://github.com/Waikato/moa/issues/273
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Version
      working-directory: ./moa
      run: mvn -v

    -  name: lscpu
       run: lscpu

    - name: Unit Tests
      working-directory: ./moa
      # Skip flakey tests 
      run: mvn -B -q test -Dtest=\!MLPTest,\!SecondTestClass

    - name: Package Jar
      working-directory: ./moa
      # Package as JAR while skipping tests, javadoc, and latex build
      run: mvn -B package -DskipTests -Dmaven.javadoc.skip=true -Dlatex.skipBuild=true

    # Upload jar file as artifact
    - name: Upload Jar
      uses: actions/upload-artifact@v4
      with:
        name: moa-jar
        path: ./moa/target/moa-*-jar-with-dependencies.jar
        if-no-files-found: error
        retention-days: 7
